// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK75nv2sJkYnsq1LrcjGKlOQEL7efsy1Q',
    appId: '1:523996877820:web:f118a58f08f2f4c17a1879',
    messagingSenderId: '523996877820',
    projectId: 'mad-activity03',
    authDomain: 'mad-activity03.firebaseapp.com',
    storageBucket: 'mad-activity03.appspot.com',
    measurementId: 'G-PM6MMW1LYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3IKi9Q1dil_oCJqq1Rs5e1PuEqVRAMuM',
    appId: '1:523996877820:android:67d2ea9bef8c4cf87a1879',
    messagingSenderId: '523996877820',
    projectId: 'mad-activity03',
    storageBucket: 'mad-activity03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaRKzzf2zj6VirbxzkLg6_3nINPcQZSWc',
    appId: '1:523996877820:ios:91ae27427068160d7a1879',
    messagingSenderId: '523996877820',
    projectId: 'mad-activity03',
    storageBucket: 'mad-activity03.appspot.com',
    iosClientId: '523996877820-5p732qeiqnhvl9l0au06djjp4gg0j2is.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaRKzzf2zj6VirbxzkLg6_3nINPcQZSWc',
    appId: '1:523996877820:ios:91ae27427068160d7a1879',
    messagingSenderId: '523996877820',
    projectId: 'mad-activity03',
    storageBucket: 'mad-activity03.appspot.com',
    iosClientId: '523996877820-5p732qeiqnhvl9l0au06djjp4gg0j2is.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApplication1',
  );
}
